Visita/Visita/Controllers/ApiRequestsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Visita.Helpers;
using ModelLibrary;
using Visita.ViewModel;

namespace Visita.Controllers
{
    public class ApiRequestsController : Controller
    {
        // GET: ApiRequests
        public async System.Threading.Tasks.Task<ActionResult> Index() {
            
                return View();
            
        }
        //GET: ApiRequests/SearchByPOI
        public async System.Threading.Tasks.Task<ActionResult> SearchByPOI()
        {
            
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/POIs");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var pois =
                JsonConvert.DeserializeObject<IEnumerable<POI>>(content);
                ViewBag.POIId = new SelectList(pois, "POIId", "nome");
                return View();
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        public async System.Threading.Tasks.Task<ActionResult> SearchByPOItoAPI(POI p)
        {
            int id = p.POIId;
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Requests/"+id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var mete =
                JsonConvert.DeserializeObject<IEnumerable<Metereologia>>(content);
                return View(mete);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

        }

        public async System.Threading.Tasks.Task<ActionResult> SearchDatenHour()
        {
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> SearchDatenHourtoAPI(viewModel vm) 
        {
            var client = WebApiHttpClient.GetClient();
            DateTime dt = vm.data_de_leitura_inicio;
            TimeSpan ts = vm.hora_de_leitura_inicio;

            String data = dt.Year + "-" + dt.Month + "-" + dt.Day;
            String hora = ts.Hours+":"+ts.Minutes+":"+ts.Seconds;

            HttpResponseMessage response = await client.GetAsync("api/Requests?dt="+data+""+"&ts="+hora);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var mete =
                JsonConvert.DeserializeObject<IEnumerable<Metereologia>>(content);
                return View(mete);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

        }

        public async System.Threading.Tasks.Task<ActionResult> SearchDatenHourRange()
        {

            return View();

        }

        public async System.Threading.Tasks.Task<ActionResult> SearchDatenHourRangetoAPI(viewModel vm)
        {
            
            var client = WebApiHttpClient.GetClient();
            DateTime dt1 = vm.data_de_leitura_inicio;
            TimeSpan ts1 = vm.hora_de_leitura_inicio;

            String data1 = dt1.Year + "-" + dt1.Month + "-" + dt1.Day;
            String hora1 = ts1.Hours + ":" + ts1.Minutes + ":" + ts1.Seconds;

            DateTime dt2 = vm.data_de_leitura_fim;
            TimeSpan ts2 = vm.hora_de_leitura_fim;

            String data2 = dt2.Year + "-" + dt2.Month + "-" + dt2.Day;
            String hora2 = ts2.Hours + ":" + ts2.Minutes + ":" + ts2.Seconds;

            HttpResponseMessage response = await client.GetAsync("api/Requests?dt1="+data1+"&dt2="+data2+"&ts1="+hora1+"&ts2="+hora2);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var mete =
                JsonConvert.DeserializeObject<IEnumerable<Metereologia>>(content);
                return View(mete);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

        }

    }
}

Visita/Visita/Views/ApiRequests/Index.cshtml
<div class="jumbotron">
    <h3><strong>Visita</strong></h3>
    <p class="lead">A aplicação Visita permite a consulta de dados de Meteorologias.
</div>
<div class="row">
    <div class="col-md-4">
        <p><img src="http://recipp.ipp.pt/retrieve/19893"></p>
    </div>
</div>

Visita/Visita/Views/ApiRequests/SearchByPOI.cshtml
@model ModelLibrary.POI

@{
    ViewBag.Title = "Search By POI";
}

<h2>Search By POI</h2>

@using (Html.BeginForm("SearchByPOItoAPI","ApiRequests",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.POIId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("POIId", null, htmlAttributes: new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.POIId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

Visita/Visita/Views/ApiRequests/SearchByPOItoAPI.cshtml
@model IEnumerable<ModelLibrary.Metereologia>

@{
    ViewBag.Title = "Search By POI to API";
}

<h2>Metereologias</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.local.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data_de_leitura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora_de_leitura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Humidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NO2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pressao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Temp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vento)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.local.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data_de_leitura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hora_de_leitura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Humidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NO2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pressao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Temp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vento)
                </td>
            </tr>
        }

    </table>

    <div>
        @Html.ActionLink("Back", "Index")
    </div>

Visita/Visita/Views/ApiRequests/SearchDatenHour.cshtml
@model Visita.ViewModel.viewModel
@{
    ViewBag.Title = "Search by Date and Hour";
}

<h2>Search by Date and Hour</h2>



@using (Html.BeginForm(Html.BeginForm("SearchDatenHourtoAPI", "ApiRequests", FormMethod.Post)))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.data_de_leitura_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_de_leitura_inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_de_leitura_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Hora</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.hora_de_leitura_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora_de_leitura_inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora_de_leitura_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back", "Index")
    </div>

Visita/Visita/Views/ApiRequests/SearchDatenHourRange.cshtml
@model Visita.ViewModel.viewModel
@{
    ViewBag.Title = "Search by Date and Hour (Range)";
}

<h2>Search by Date and Hour (Range)</h2>


@using (Html.BeginForm(Html.BeginForm("SearchDatenHourRangetoAPI", "ApiRequests", FormMethod.Post)))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Data de Início:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.data_de_leitura_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_de_leitura_inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_de_leitura_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Data de Fim:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.data_de_leitura_fim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_de_leitura_fim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_de_leitura_fim, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Hora de Início</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.hora_de_leitura_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora_de_leitura_inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora_de_leitura_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Hora de Fim</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.hora_de_leitura_fim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hora_de_leitura_fim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hora_de_leitura_fim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

Visita/Visita/Views/ApiRequests/SearchDatenHourRangetoAPI.cshtml
@model IEnumerable<ModelLibrary.Metereologia>

@{
    ViewBag.Title = "Search Date and Hour to API (Range)";
}

<h2>Metereologias</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.local.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_de_leitura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_de_leitura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Humidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pressao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Temp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vento)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.local.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_de_leitura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_de_leitura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Humidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NO2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pressao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Temp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vento)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back", "Index")
</div>

Visita/Visita/Views/ApiRequests/SearchDatenHourtoAPI.cshtml
@model IEnumerable<ModelLibrary.Metereologia>

@{
    ViewBag.Title = "Search Date and Hour to API";
}

<h2>Metereologias</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.local.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_de_leitura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_de_leitura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Humidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NO2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pressao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Temp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vento)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.local.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_de_leitura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_de_leitura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Humidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NO2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pressao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Temp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vento)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back", "Index")
</div>